# Generated by Django 5.2.15 on 2026-07-03 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapbox_baselayer", "0015_alter_baselayertile_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mapbaselayer",
            old_name="map_box_url",
            new_name="style_url",
        ),
    ]
