# Generated by Django 5.2.15 on 2026-07-06 09:52

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import mapbox_baselayer.models


class Migration(migrations.Migration):
    dependencies = [
        ("mapbox_baselayer", "0016_rename_map_box_url_mapbaselayer_style_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMTile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "pmtiles_file",
                    models.FileField(
                        upload_to=mapbox_baselayer.models.pmtile_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pmtiles"]
                            )
                        ],
                        verbose_name="PMTiles file",
                    ),
                ),
                (
                    "pmtiles_style",
                    models.FileField(
                        upload_to=mapbox_baselayer.models.pmtile_path_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["json"]
                            )
                        ],
                        verbose_name="PMTiles style",
                    ),
                ),
                (
                    "min_zoom",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Minimum zoom level"
                    ),
                ),
                (
                    "max_zoom",
                    models.PositiveSmallIntegerField(
                        default=18, verbose_name="Maximum zoom level"
                    ),
                ),
                ("bbox", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_tilesets",
                        to="mapbox_baselayer.mapbaselayer",
                        verbose_name="Layer",
                    ),
                ),
            ],
        ),
    ]
