# Generated by Django 5.2.15 on 2026-07-07 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapbox_baselayer", "0017_pmtile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pmtile",
            options={"ordering": ("name",)},
        ),
    ]
