# Generated by Django 5.2.15 on 2026-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapbox_baselayer", "0018_alter_pmtile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapbaselayer",
            name="base_layer_type",
            field=models.CharField(
                choices=[("mapbox", "Style URL"), ("raster", "Raster tiles")],
                db_index=True,
                max_length=25,
                verbose_name="Layer type",
            ),
        ),
        migrations.AlterField(
            model_name="mapbaselayer",
            name="tile_size",
            field=models.PositiveSmallIntegerField(
                default=256,
                help_text="Tile size. Often 256 for raster tiles, 512 for vector tiles.",
                verbose_name="Tile size",
            ),
        ),
    ]
